version: '3'
services:
  db:
    image: postgres:13
    env_file:
      - .envs/.env.local
    volumes:
      - /home/tyshbyr/postgresql/data:/var/lib/postgresql/data

  django:
    env_file:
      - .envs/.env.local
    build: app
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - django
    ports:
      - "80:80"
volumes:
  static_volume:
  media_volume:
